PRODUCTS = [
    {
        "id": "shopmesh-1",
        "title": "Nike Revolution 7 Running Shoes",
        "brand": "Nike",
        "category": "Running Shoes",
        "store_id": "myntra",
        "store_name": "Myntra",
        "price": 4299,
        "mrp": 5999,
        "currency": "INR",
        "rating": 4.4,
        "rating_count": 1240,
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-2",
        "title": "Adidas Runfalcon 5 Running Shoes",
        "brand": "Adidas",
        "category": "Running Shoes",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 3899,
        "mrp": 5499,
        "currency": "INR",
        "rating": 4.3,
        "rating_count": 980,
        "image": "https://images.unsplash.com/photo-1552346154-21d32810aba3",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-3",
        "title": "Puma Softride Enzo Running Shoes",
        "brand": "Puma",
        "category": "Running Shoes",
        "store_id": "flipkart",
        "store_name": "Flipkart",
        "price": 3499,
        "mrp": 4999,
        "currency": "INR",
        "rating": 4.2,
        "rating_count": 756,
        "image": "https://images.unsplash.com/photo-1608231387042-66d1773070a5",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-4",
        "title": "New Balance Fresh Foam X 1080",
        "brand": "New Balance",
        "category": "Running Shoes",
        "store_id": "ajio",
        "store_name": "Ajio",
        "price": 8999,
        "mrp": 12999,
        "currency": "INR",
        "rating": 4.6,
        "rating_count": 2150,
        "image": "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-5",
        "title": "ASICS Gel-Contend 9 Running Shoes",
        "brand": "ASICS",
        "category": "Running Shoes",
        "store_id": "myntra",
        "store_name": "Myntra",
        "price": 4599,
        "mrp": 6499,
        "currency": "INR",
        "rating": 4.5,
        "rating_count": 1870,
        "image": "https://images.unsplash.com/photo-1460353581641-37baddab0fa2",
        "url": "https://example.com",
        "availability": "in_stock",
    },

    {
        "id": "shopmesh-6",
        "title": "Apple iPhone 15 128GB",
        "brand": "Apple",
        "category": "Smartphones",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 59999,
        "mrp": 69900,
        "currency": "INR",
        "rating": 4.6,
        "rating_count": 8450,
        "image": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-7",
        "title": "Samsung Galaxy S24 256GB",
        "brand": "Samsung",
        "category": "Smartphones",
        "store_id": "flipkart",
        "store_name": "Flipkart",
        "price": 64999,
        "mrp": 79999,
        "currency": "INR",
        "rating": 4.5,
        "rating_count": 6320,
        "image": "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-8",
        "title": "OnePlus 13R 5G",
        "brand": "OnePlus",
        "category": "Smartphones",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 42999,
        "mrp": 49999,
        "currency": "INR",
        "rating": 4.4,
        "rating_count": 4210,
        "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-9",
        "title": "Google Pixel 9",
        "brand": "Google",
        "category": "Smartphones",
        "store_id": "flipkart",
        "store_name": "Flipkart",
        "price": 67999,
        "mrp": 79999,
        "currency": "INR",
        "rating": 4.5,
        "rating_count": 2980,
        "image": "https://images.unsplash.com/photo-1598327105666-5b89351aff97",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-10",
        "title": "Nothing Phone 3a Pro",
        "brand": "Nothing",
        "category": "Smartphones",
        "store_id": "croma",
        "store_name": "Croma",
        "price": 31999,
        "mrp": 36999,
        "currency": "INR",
        "rating": 4.3,
        "rating_count": 1540,
        "image": "https://images.unsplash.com/photo-1523206489230-c012c64b2b48",
        "url": "https://example.com",
        "availability": "in_stock",
    },

    {
        "id": "shopmesh-11",
        "title": "Sony WH-1000XM5 Wireless Headphones",
        "brand": "Sony",
        "category": "Headphones",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 24990,
        "mrp": 34990,
        "currency": "INR",
        "rating": 4.7,
        "rating_count": 9850,
        "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-12",
        "title": "Apple AirPods Pro 2",
        "brand": "Apple",
        "category": "Earbuds",
        "store_id": "croma",
        "store_name": "Croma",
        "price": 18999,
        "mrp": 24900,
        "currency": "INR",
        "rating": 4.6,
        "rating_count": 7210,
        "image": "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-13",
        "title": "Samsung Galaxy Buds3 Pro",
        "brand": "Samsung",
        "category": "Earbuds",
        "store_id": "flipkart",
        "store_name": "Flipkart",
        "price": 14999,
        "mrp": 19999,
        "currency": "INR",
        "rating": 4.4,
        "rating_count": 3420,
        "image": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-14",
        "title": "JBL Tune 770NC Wireless Headphones",
        "brand": "JBL",
        "category": "Headphones",
        "store_id": "myntra",
        "store_name": "Myntra",
        "price": 4999,
        "mrp": 7999,
        "currency": "INR",
        "rating": 4.3,
        "rating_count": 5120,
        "image": "https://images.unsplash.com/photo-1484704849700-f032a568e944",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-15",
        "title": "boAt Airdopes 141",
        "brand": "boAt",
        "category": "Earbuds",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 1299,
        "mrp": 4490,
        "currency": "INR",
        "rating": 4.1,
        "rating_count": 45200,
        "image": "https://images.unsplash.com/photo-1598331668826-20cecc596b86",
        "url": "https://example.com",
        "availability": "in_stock",
    },

    {
        "id": "shopmesh-16",
        "title": "Dell Inspiron 15 Laptop",
        "brand": "Dell",
        "category": "Laptops",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 54990,
        "mrp": 69990,
        "currency": "INR",
        "rating": 4.3,
        "rating_count": 2180,
        "image": "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-17",
        "title": "HP Pavilion 14 Laptop",
        "brand": "HP",
        "category": "Laptops",
        "store_id": "flipkart",
        "store_name": "Flipkart",
        "price": 58990,
        "mrp": 74990,
        "currency": "INR",
        "rating": 4.4,
        "rating_count": 1840,
        "image": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-18",
        "title": "Lenovo IdeaPad Slim 5",
        "brand": "Lenovo",
        "category": "Laptops",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 62990,
        "mrp": 79990,
        "currency": "INR",
        "rating": 4.5,
        "rating_count": 2310,
        "image": "https://images.unsplash.com/photo-1531297484001-80022131f5a1",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-19",
        "title": "ASUS Vivobook 15 OLED",
        "brand": "ASUS",
        "category": "Laptops",
        "store_id": "croma",
        "store_name": "Croma",
        "price": 67990,
        "mrp": 84990,
        "currency": "INR",
        "rating": 4.5,
        "rating_count": 1670,
        "image": "https://images.unsplash.com/photo-1602080858428-57174f9431cf",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-20",
        "title": "Acer Aspire Lite",
        "brand": "Acer",
        "category": "Laptops",
        "store_id": "reliance-digital",
        "store_name": "Reliance Digital",
        "price": 42990,
        "mrp": 59990,
        "currency": "INR",
        "rating": 4.2,
        "rating_count": 1430,
        "image": "https://images.unsplash.com/photo-1593642532400-2682810df593",
        "url": "https://example.com",
        "availability": "in_stock",
    },

    {
        "id": "shopmesh-21",
        "title": "Apple Watch Series 10",
        "brand": "Apple",
        "category": "Smartwatches",
        "store_id": "croma",
        "store_name": "Croma",
        "price": 42900,
        "mrp": 46900,
        "currency": "INR",
        "rating": 4.7,
        "rating_count": 3120,
        "image": "https://images.unsplash.com/photo-1546868871-7041f2a55e12",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-22",
        "title": "Samsung Galaxy Watch 7",
        "brand": "Samsung",
        "category": "Smartwatches",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 29999,
        "mrp": 36999,
        "currency": "INR",
        "rating": 4.5,
        "rating_count": 2140,
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-23",
        "title": "Garmin Forerunner 165",
        "brand": "Garmin",
        "category": "Smartwatches",
        "store_id": "flipkart",
        "store_name": "Flipkart",
        "price": 24990,
        "mrp": 29990,
        "currency": "INR",
        "rating": 4.6,
        "rating_count": 1240,
        "image": "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-24",
        "title": "Noise ColorFit Pro 5",
        "brand": "Noise",
        "category": "Smartwatches",
        "store_id": "myntra",
        "store_name": "Myntra",
        "price": 2999,
        "mrp": 5999,
        "currency": "INR",
        "rating": 4.2,
        "rating_count": 12450,
        "image": "https://images.unsplash.com/photo-1579586337278-3befd40fd17a",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-25",
        "title": "boAt Wave Sigma 3",
        "brand": "boAt",
        "category": "Smartwatches",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 1799,
        "mrp": 4999,
        "currency": "INR",
        "rating": 4.1,
        "rating_count": 8750,
        "image": "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9",
        "url": "https://example.com",
        "availability": "in_stock",
    },

    {
        "id": "shopmesh-26",
        "title": "Levi's 511 Slim Fit Jeans",
        "brand": "Levi's",
        "category": "Jeans",
        "store_id": "myntra",
        "store_name": "Myntra",
        "price": 2399,
        "mrp": 3999,
        "currency": "INR",
        "rating": 4.4,
        "rating_count": 5620,
        "image": "https://images.unsplash.com/photo-1542272604-787c3835535d",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-27",
        "title": "Roadster Men Skinny Fit Jeans",
        "brand": "Roadster",
        "category": "Jeans",
        "store_id": "myntra",
        "store_name": "Myntra",
        "price": 999,
        "mrp": 2499,
        "currency": "INR",
        "rating": 4.1,
        "rating_count": 8320,
        "image": "https://images.unsplash.com/photo-1541099649105-f69ad21f3246",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-28",
        "title": "Wrangler Regular Fit Jeans",
        "brand": "Wrangler",
        "category": "Jeans",
        "store_id": "ajio",
        "store_name": "Ajio",
        "price": 1899,
        "mrp": 3499,
        "currency": "INR",
        "rating": 4.3,
        "rating_count": 3210,
        "image": "https://images.unsplash.com/photo-1475178626620-a4d074967452",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-29",
        "title": "Levi's Women High Rise Straight Jeans",
        "brand": "Levi's",
        "category": "Jeans",
        "store_id": "myntra",
        "store_name": "Myntra",
        "price": 2599,
        "mrp": 4299,
        "currency": "INR",
        "rating": 4.5,
        "rating_count": 2740,
        "image": "https://images.unsplash.com/photo-1548883354-7622d03aca27",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-30",
        "title": "H&M Relaxed Fit Cargo Trousers",
        "brand": "H&M",
        "category": "Trousers",
        "store_id": "ajio",
        "store_name": "Ajio",
        "price": 1799,
        "mrp": 2999,
        "currency": "INR",
        "rating": 4.2,
        "rating_count": 1940,
        "image": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f",
        "url": "https://example.com",
        "availability": "in_stock",
    },

    {
        "id": "shopmesh-31",
        "title": "Nike Dri-FIT Training T-Shirt",
        "brand": "Nike",
        "category": "T-Shirts",
        "store_id": "myntra",
        "store_name": "Myntra",
        "price": 1499,
        "mrp": 2499,
        "currency": "INR",
        "rating": 4.5,
        "rating_count": 3210,
        "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-32",
        "title": "Adidas Essentials Cotton T-Shirt",
        "brand": "Adidas",
        "category": "T-Shirts",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 1199,
        "mrp": 1999,
        "currency": "INR",
        "rating": 4.3,
        "rating_count": 2850,
        "image": "https://images.unsplash.com/photo-1503341504253-dff4815485f1",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-33",
        "title": "Puma Essentials Logo T-Shirt",
        "brand": "Puma",
        "category": "T-Shirts",
        "store_id": "flipkart",
        "store_name": "Flipkart",
        "price": 999,
        "mrp": 1799,
        "currency": "INR",
        "rating": 4.2,
        "rating_count": 1760,
        "image": "https://images.unsplash.com/photo-1583743814966-8936f37f4678",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-34",
        "title": "H&M Oversized Printed T-Shirt",
        "brand": "H&M",
        "category": "T-Shirts",
        "store_id": "ajio",
        "store_name": "Ajio",
        "price": 799,
        "mrp": 1499,
        "currency": "INR",
        "rating": 4.1,
        "rating_count": 1290,
        "image": "https://images.unsplash.com/photo-1529139574466-a303027c1d8b",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-35",
        "title": "Levi's Graphic Cotton T-Shirt",
        "brand": "Levi's",
        "category": "T-Shirts",
        "store_id": "myntra",
        "store_name": "Myntra",
        "price": 1299,
        "mrp": 2299,
        "currency": "INR",
        "rating": 4.4,
        "rating_count": 2180,
        "image": "https://images.unsplash.com/photo-1576566588028-4147f3842f27",
        "url": "https://example.com",
        "availability": "in_stock",
    },

    {
        "id": "shopmesh-36",
        "title": "Nike Air Max Dn Sneakers",
        "brand": "Nike",
        "category": "Sneakers",
        "store_id": "myntra",
        "store_name": "Myntra",
        "price": 8999,
        "mrp": 12999,
        "currency": "INR",
        "rating": 4.5,
        "rating_count": 1680,
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-37",
        "title": "Adidas Forum Low Sneakers",
        "brand": "Adidas",
        "category": "Sneakers",
        "store_id": "ajio",
        "store_name": "Ajio",
        "price": 4999,
        "mrp": 7999,
        "currency": "INR",
        "rating": 4.4,
        "rating_count": 2410,
        "image": "https://images.unsplash.com/photo-1607522370275-f14206abe5d3",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-38",
        "title": "Puma Caven 2.0 Sneakers",
        "brand": "Puma",
        "category": "Sneakers",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 2999,
        "mrp": 5499,
        "currency": "INR",
        "rating": 4.3,
        "rating_count": 1980,
        "image": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-39",
        "title": "Vans Old Skool Sneakers",
        "brand": "Vans",
        "category": "Sneakers",
        "store_id": "myntra",
        "store_name": "Myntra",
        "price": 4499,
        "mrp": 6499,
        "currency": "INR",
        "rating": 4.6,
        "rating_count": 3420,
        "image": "https://images.unsplash.com/photo-1529810313688-4f92f05b0f2d",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-40",
        "title": "Converse Chuck Taylor All Star",
        "brand": "Converse",
        "category": "Sneakers",
        "store_id": "ajio",
        "store_name": "Ajio",
        "price": 3799,
        "mrp": 4999,
        "currency": "INR",
        "rating": 4.5,
        "rating_count": 2750,
        "image": "https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3",
        "url": "https://example.com",
        "availability": "in_stock",
    },

    {
        "id": "shopmesh-41",
        "title": "Sony Bravia 55 Inch 4K TV",
        "brand": "Sony",
        "category": "Televisions",
        "store_id": "croma",
        "store_name": "Croma",
        "price": 69990,
        "mrp": 99990,
        "currency": "INR",
        "rating": 4.6,
        "rating_count": 3240,
        "image": "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-42",
        "title": "Samsung Crystal 4K 55 Inch TV",
        "brand": "Samsung",
        "category": "Televisions",
        "store_id": "flipkart",
        "store_name": "Flipkart",
        "price": 47999,
        "mrp": 69999,
        "currency": "INR",
        "rating": 4.4,
        "rating_count": 4520,
        "image": "https://images.unsplash.com/photo-1593784991095-a205069470b6",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-43",
        "title": "LG 55 Inch OLED Smart TV",
        "brand": "LG",
        "category": "Televisions",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 89990,
        "mrp": 119990,
        "currency": "INR",
        "rating": 4.7,
        "rating_count": 2670,
        "image": "https://images.unsplash.com/photo-1461151304267-38535e780c79",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-44",
        "title": "TCL 43 Inch 4K Smart TV",
        "brand": "TCL",
        "category": "Televisions",
        "store_id": "reliance-digital",
        "store_name": "Reliance Digital",
        "price": 28999,
        "mrp": 39999,
        "currency": "INR",
        "rating": 4.2,
        "rating_count": 1860,
        "image": "https://images.unsplash.com/photo-1598032895397-b9472444bf93",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-45",
        "title": "OnePlus 50 Inch 4K QLED TV",
        "brand": "OnePlus",
        "category": "Televisions",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 32999,
        "mrp": 49999,
        "currency": "INR",
        "rating": 4.3,
        "rating_count": 2140,
        "image": "https://images.unsplash.com/photo-1601944177325-f8867652837f",
        "url": "https://example.com",
        "availability": "in_stock",
    },

    {
        "id": "shopmesh-46",
        "title": "Philips 1.5L Air Fryer",
        "brand": "Philips",
        "category": "Kitchen Appliances",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 4999,
        "mrp": 7995,
        "currency": "INR",
        "rating": 4.4,
        "rating_count": 5120,
        "image": "https://images.unsplash.com/photo-1585515320310-259814833e62",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-47",
        "title": "Prestige Electric Kettle 1.5L",
        "brand": "Prestige",
        "category": "Kitchen Appliances",
        "store_id": "flipkart",
        "store_name": "Flipkart",
        "price": 1299,
        "mrp": 1995,
        "currency": "INR",
        "rating": 4.3,
        "rating_count": 6340,
        "image": "https://images.unsplash.com/photo-1594213114663-d94db9b1714f",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-48",
        "title": "Bajaj Majesty Mixer Grinder",
        "brand": "Bajaj",
        "category": "Kitchen Appliances",
        "store_id": "croma",
        "store_name": "Croma",
        "price": 2999,
        "mrp": 4499,
        "currency": "INR",
        "rating": 4.2,
        "rating_count": 2980,
        "image": "https://images.unsplash.com/photo-1570222094114-d054a817e56b",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-49",
        "title": "Dyson V12 Detect Slim Vacuum",
        "brand": "Dyson",
        "category": "Home Appliances",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 54900,
        "mrp": 64900,
        "currency": "INR",
        "rating": 4.6,
        "rating_count": 1430,
        "image": "https://images.unsplash.com/photo-1558317374-067fb5f30001",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-50",
        "title": "Eureka Forbes Quick Clean Vacuum",
        "brand": "Eureka Forbes",
        "category": "Home Appliances",
        "store_id": "flipkart",
        "store_name": "Flipkart",
        "price": 4999,
        "mrp": 7999,
        "currency": "INR",
        "rating": 4.1,
        "rating_count": 3240,
        "image": "https://images.unsplash.com/photo-1581578731548-c64695cc6952",
        "url": "https://example.com",
        "availability": "in_stock",
    },

    {
        "id": "shopmesh-51",
        "title": "Adidas Ultraboost Light Running Shoes",
        "brand": "Adidas",
        "category": "Running Shoes",
        "store_id": "myntra",
        "store_name": "Myntra",
        "price": 10999,
        "mrp": 17999,
        "currency": "INR",
        "rating": 4.7,
        "rating_count": 3420,
        "image": "https://images.unsplash.com/photo-1556906781-9a412961c28c",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-52",
        "title": "Nike Pegasus 41 Running Shoes",
        "brand": "Nike",
        "category": "Running Shoes",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 7499,
        "mrp": 10995,
        "currency": "INR",
        "rating": 4.6,
        "rating_count": 2870,
        "image": "https://images.unsplash.com/photo-1553778263-73a83bab9b0c",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-53",
        "title": "ASICS Gel-Kayano 31",
        "brand": "ASICS",
        "category": "Running Shoes",
        "store_id": "flipkart",
        "store_name": "Flipkart",
        "price": 9999,
        "mrp": 14999,
        "currency": "INR",
        "rating": 4.7,
        "rating_count": 1980,
        "image": "https://images.unsplash.com/photo-1518002171953-a080ee817e1f",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-54",
        "title": "Puma Deviate Nitro 3",
        "brand": "Puma",
        "category": "Running Shoes",
        "store_id": "ajio",
        "store_name": "Ajio",
        "price": 6999,
        "mrp": 11999,
        "currency": "INR",
        "rating": 4.5,
        "rating_count": 1120,
        "image": "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-55",
        "title": "Reebok Floatride Energy 5",
        "brand": "Reebok",
        "category": "Running Shoes",
        "store_id": "myntra",
        "store_name": "Myntra",
        "price": 3999,
        "mrp": 7999,
        "currency": "INR",
        "rating": 4.3,
        "rating_count": 1670,
        "image": "https://images.unsplash.com/photo-1539185441755-769473a23570",
        "url": "https://example.com",
        "availability": "in_stock",
    },

    {
        "id": "shopmesh-56",
        "title": "Samsung 990 Pro 1TB NVMe SSD",
        "brand": "Samsung",
        "category": "Computer Accessories",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 8499,
        "mrp": 12999,
        "currency": "INR",
        "rating": 4.7,
        "rating_count": 5430,
        "image": "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-57",
        "title": "Logitech MX Master 3S Mouse",
        "brand": "Logitech",
        "category": "Computer Accessories",
        "store_id": "flipkart",
        "store_name": "Flipkart",
        "price": 7999,
        "mrp": 9995,
        "currency": "INR",
        "rating": 4.6,
        "rating_count": 4320,
        "image": "https://images.unsplash.com/photo-1527814050087-3793815479db",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-58",
        "title": "Keychron K2 Mechanical Keyboard",
        "brand": "Keychron",
        "category": "Computer Accessories",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 7990,
        "mrp": 9990,
        "currency": "INR",
        "rating": 4.5,
        "rating_count": 2150,
        "image": "https://images.unsplash.com/photo-1587829741301-dc798b83add3",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-59",
        "title": "Dell 27 Inch Full HD Monitor",
        "brand": "Dell",
        "category": "Computer Accessories",
        "store_id": "croma",
        "store_name": "Croma",
        "price": 15999,
        "mrp": 21999,
        "currency": "INR",
        "rating": 4.4,
        "rating_count": 1890,
        "image": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-60",
        "title": "Amazon Basics Laptop Backpack",
        "brand": "Amazon Basics",
        "category": "Bags",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 1299,
        "mrp": 2499,
        "currency": "INR",
        "rating": 4.3,
        "rating_count": 8650,
        "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62",
        "url": "https://example.com",
        "availability": "in_stock",
    },
]