PRODUCTS = [
    {
        "id": "shopmesh-1",
        "title": "Nike Revolution 7 Running Shoes",
        "brand": "Nike",
        "category": "Running Shoes",
        "store_id": "myntra",
        "store_name": "Myntra",
        "price": 4299,
        "mrp": 5999,
        "currency": "INR",
        "rating": 4.4,
        "rating_count": 1240,
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-2",
        "title": "Adidas Runfalcon 5 Running Shoes",
        "brand": "Adidas",
        "category": "Running Shoes",
        "store_id": "amazon",
        "store_name": "Amazon",
        "price": 3899,
        "mrp": 5499,
        "currency": "INR",
        "rating": 4.3,
        "rating_count": 980,
        "image": "https://images.unsplash.com/photo-1552346154-21d32810aba3",
        "url": "https://example.com",
        "availability": "in_stock",
    },
    {
        "id": "shopmesh-3",
        "title": "Puma Softride Enzo Running Shoes",
        "brand": "Puma",
        "category": "Running Shoes",
        "store_id": "flipkart",
        "store_name": "Flipkart",
        "price": 3499,
        "mrp": 4999,
        "currency": "INR",
        "rating": 4.2,
        "rating_count": 756,
        "image": "https://images.unsplash.com/photo-1608231387042-66d1773070a5",
        "url": "https://example.com",
        "availability": "in_stock",
    },
]